apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-frontend-deployment
spec:
  selector:
    matchLabels:
      app: portal-frontend
  template:
    metadata:
      labels:
        app: portal-frontend
    spec:
      containers:
        - image: robekeane/portal-frontend:0.2
          name: portal-frontend-con
