apiVersion: v1
kind: Service
metadata:
  name: portal-frontend-service
  labels:
    app: portal-frontend
spec:
  type: NodePort
  selector:
      app: portal-frontend
  ports:
  - protocol : TCP
    nodePort: 30800
    port: 80
    targetPort: 80
