apiVersion: v1
kind: Service
metadata:
  name: portal-backend-service
  labels:
    app: portal-backend
spec:
  type: NodePort
  selector:
      app: portal-backend
  ports:
  - protocol : TCP
    nodePort: 30900
    port: 9000
    targetPort: 9000
